name: App Update Check

on:
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
        
      - name: Check/Download/Patch New Version
        run: |
          npm install
          node index.js
        env:
          key: ${{ secrets.KEY }}

      - name: Read Version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt

      - name: Commit Version
        run: |
          git config --global user.name 'thororen1234'
          git config --global user.email '78185467+thororen1234@users.noreply.github.com'
          git add version.txt
          git commit -m "New Version Detected - ${{ steps.version.outputs.content }}"
          git push

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.content }}
          files: patchapk/merged-360-lspatched.apk
          body: New Version Detected - ${{ steps.version.outputs.content }}
